---
title: "p8105_hw6_jdv2118"
author: "Justin Vargas"
output: github_document
---

# Loading Libraries and Setting Graphic Settings

```{r}
library(tidyverse)

library(modelr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d

scale_fill_discrete = scale_fill_viridis_d
```

# Problem 2

```{r}
homicide_data = 
  read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    result = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Closed by arrest"      ~ 1,
      disposition == "Open/No arrest"        ~ 0
      ),
    victim_age = as.numeric(victim_age)
  ) %>% 
  filter(city_state != "Dallas, TX",
         city_state != "Phoenix, AZ",
         city_state != "Kansas City, MO",
         city_state != "Tulsa, AL",
victim_race %in% c("White", "Black"),
victim_sex != "Unknown") %>% 
  select(city_state, result, victim_age, victim_race, victim_sex)
```

```{r}
baltimore_glm =
  homicide_data %>% 
  filter(city_state == "Baltimore, MD")

glm(result ~ victim_age + victim_sex + victim_race, 
    data = baltimore_glm,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    ci_lower = exp(estimate - 1.96 * std.error),
    ci_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("ci")) %>% 
  knitr::kable(digits = 3)
```

```{r}
cities_glm = 
  homicide_data %>% 
  nest(data = -city_state) %>% 
  mutate(
    city_models = 
      map(.x = data, ~glm(result ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),
    result = map(city_models, broom::tidy)
  ) %>% 
  select(city_state, result) %>% 
  unnest(result) %>% 
  mutate(
    OR = exp(estimate),
    ci_lower = exp(estimate - 1.96 * std.error),
    ci_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("ci")) %>%
  filter(term == "victim_sexMale")
  
cities_glm
```

```{r}
cities_plot =
  cities_glm %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper)) + 
  labs(
    x = "City and State Names",
    y = "Odds Ratio",
    title = "The Odds Ratio for Each City and State"
  ) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

cities_plot
```

